# Generated by Django 2.1.2 on 2018-11-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20180513_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounttypes', to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'account type',
                'verbose_name_plural': 'account types',
                'default_related_name': 'accounttypes',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='projects.AccountType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'password',
                'verbose_name_plural': 'passwords',
                'default_related_name': 'passwords',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'default_related_name': 'projects',
            },
        ),
        migrations.AddField(
            model_name='password',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='projects.Project'),
        ),
    ]
