# Generated by Django 2.1.2 on 2018-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181013_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='password',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
